### ISSUE TITLE
Direct RGB Mode

### ISSUE THREAD

**Issue by thojo0** [moritz-h/satisfactory-lightcontrol#4]
I would like an extra mode where every light has its own 3 Channels.
Its a simpler setup and better working with other special software which is not DMXControl.

**Comment by moritz-h** [comment]
The current mode has nothing to do with DMXControl, but is based on the way the lights are controlled within Satisfactory. Compare to the Light Control Panel in game. There is an intensity slider and a color slot, with globally shared colors, no possibility to directly set an RGB color.

Nevertheless, I may have already found a more hacky way around the official interface to support other modes in the next version, which is already in development, but requires some more testing until I can release it.

**Comment by moritz-h** [comment]
Implemented in 13f7d3df4907bcc6c66804de121ca54d3665f153.
